// Thin client over the file-explorer backend. Base URL is injected by the
// Electron preload; falls back to localhost for a plain browser in dev.
const BASE = (typeof window !== 'undefined' && window.env?.apiBaseUrl) || 'http://localhost:3001'

async function json(res) {
  if (!res.ok) {
    const body = await res.json().catch(() => null)
    throw new Error(body?.error?.message || `Request failed (${res.status})`)
  }
  return res.status === 204 ? null : res.json()
}

const q = (path) => `?path=${encodeURIComponent(path ?? '')}`

export const api = {
  async waitUntilReady({ retries = 40, delayMs = 250 } = {}) {
    for (let i = 0; i < retries; i++) {
      try {
        if ((await fetch(`${BASE}/health`)).ok) return true
      } catch {
        // backend not up yet
      }
      await new Promise((r) => setTimeout(r, delayMs))
    }
    throw new Error('Backend did not start in time')
  },

  list(path = '') {
    return fetch(`${BASE}/api/fs${q(path)}`).then(json)
  },

  createFolder(path, name) {
    return fetch(`${BASE}/api/fs/folder`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ path, name }),
    }).then(json)
  },

  createFile(path, name) {
    return fetch(`${BASE}/api/fs/file`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ path, name }),
    }).then(json)
  },

  duplicate(path) {
    return fetch(`${BASE}/api/fs/duplicate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ path }),
    }).then(json)
  },

  copy(paths, destDir) {
    return fetch(`${BASE}/api/fs/copy`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ paths, destDir }),
    }).then(json)
  },

  move(paths, destDir) {
    return fetch(`${BASE}/api/fs/move`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ paths, destDir }),
    }).then(json)
  },

  upload(path, file) {
    const form = new FormData()
    form.append('path', path ?? '')
    form.append('file', file)
    return fetch(`${BASE}/api/fs/upload`, { method: 'POST', body: form }).then(json)
  },

  rename(path, name) {
    return fetch(`${BASE}/api/fs/rename`, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ path, name }),
    }).then(json)
  },

  remove(path) {
    return fetch(`${BASE}/api/fs${q(path)}`, { method: 'DELETE' }).then(json)
  },

  /** Direct URL to a file's bytes — usable as an <img> src for previews. */
  contentUrl(path) {
    return `${BASE}/api/fs/content${q(path)}`
  },

  /** URL to a small cached thumbnail (images + videos), generated by the backend. */
  thumbnailUrl(path, size = 256) {
    return `${BASE}/api/fs/thumbnail${q(path)}&w=${size}`
  },

  /** Fetch a video's hover-preview sprite sheet + its tiling metadata. */
  async storyboard(path) {
    const res = await fetch(`${BASE}/api/fs/storyboard${q(path)}`)
    if (!res.ok) throw new Error('No storyboard')
    const url = URL.createObjectURL(await res.blob())
    return {
      url,
      cols: Number(res.headers.get('X-SB-Cols')),
      rows: Number(res.headers.get('X-SB-Rows')),
      interval: Number(res.headers.get('X-SB-Interval')),
      count: Number(res.headers.get('X-SB-Count')),
    }
  },

  async download(entry) {
    const res = await fetch(`${BASE}/api/fs/content${q(entry.path)}`)
    if (!res.ok) throw new Error('Download failed')
    const blob = await res.blob()
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = entry.name
    a.click()
    URL.revokeObjectURL(url)
  },

  favorites: {
    list() {
      return fetch(`${BASE}/api/favorites`).then(json)
    },
    add(path) {
      return fetch(`${BASE}/api/favorites`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ path }),
      }).then(json)
    },
    remove(path) {
      return fetch(`${BASE}/api/favorites${q(path)}`, { method: 'DELETE' }).then(json)
    },
  },

  tags: {
    list() {
      return fetch(`${BASE}/api/tags`).then(json)
    },
    create(name, color, parentId) {
      return fetch(`${BASE}/api/tags`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ name, color, parentId }),
      }).then(json)
    },
    update(id, changes) {
      return fetch(`${BASE}/api/tags/${id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(changes),
      }).then(json)
    },
    remove(id) {
      return fetch(`${BASE}/api/tags/${id}`, { method: 'DELETE' }).then(json)
    },
    assignments() {
      return fetch(`${BASE}/api/tags/assignments`).then(json)
    },
    files(id) {
      return fetch(`${BASE}/api/tags/${id}/files`).then(json)
    },
    assign(path, tagId) {
      return fetch(`${BASE}/api/tags/assignments`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ path, tagId }),
      }).then(json)
    },
    unassign(path, tagId) {
      return fetch(
        `${BASE}/api/tags/assignments${q(path)}&tagId=${encodeURIComponent(tagId)}`,
        { method: 'DELETE' },
      ).then(json)
    },
  },
}
